# Generated by Django 5.2.7 on 2025-10-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_full_name_alter_user_email_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='Mobile Number'),
        ),
    ]
